spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hsmy_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    #password: sq123456
    password: 123456
  
  redis:
    host: localhost
    port: 6379
    database: 0
    password: 
    timeout: 5000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.hsmy: debug
    org.springframework.web: debug
    org.mybatis: debug

file:
  storage:
    local:
      root-path: ./uploads
      url-prefix: /api/file/uploads

communication:
  sms:
    enabled: false
  email:
    enabled: false
    host: smtp.163.com
    port: 25
    from: dev@test.com
    password: dev_password
    from-name: 敲敲木鱼-开发环境

wechatpay:
  enabled: false
  app-id: 123
  mch-id: 123
  serial-no: abc123
  api-v3-key: 123
  notify-url: 'http://localhost:8080/api/v1.0/payment/wechat/notify'
  description: '功德充值'